version: '2'
services:
    microservicios-app:
        image: microservicios
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://microservicios-postgresql:5432/microservicios
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    microservicios-postgresql:
        extends:
            file: postgresql.yml
            service: microservicios-postgresql
